name: Build and Test
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
          version: ["7.4", "8.1", "8.2", "8.3"]
          arch: [x64]
          ts: [ts]
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Checkout mailparse
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup PHP ${{ matrix.php }}
        id: setup-php-sdk
        uses: php/setup-php-sdk@v0.8
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php-sdk.outputs.toolset}}
      - name: Build mailparse
        run: |
          phpize
          ./configure --enable-mailparse --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}
          nmake
      - name: package
        run: |
          md binaries
          Get-ChildItem -Recurse -Filter "php_mailparse.dll" | ForEach-Object {Copy-Item -Path $_.FullName -Destination "binaries"}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mailparse-${{matrix.php}}-x64-${{matrix.ts}}
          path: binaries
      - name: test
        run: nmake test TESTS="-d extension=${{steps.setup-php-sdk.outputs.prefix}}\ext\php_mbstring.dll --show-diff tests"
