name: Build and Test
on: [push, pull_request]
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          os: [ windows-2019 ]
          version: ["7.4", "8.1", "8.2", "8.3"]
          arch: [x64]
          ts: [ts]
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Checkout mailparse
        uses: actions/checkout@v2
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
        env:
          phpts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: phpize
      - name: configure
        run: configure --enable-mailparse --with-prefix=${{steps.setup-php.outputs.prefix}}
      - name: make
        run: nmake
      - name: test
        run: nmake test TESTS="-d extension=${{steps.setup-php.outputs.prefix}}\ext\php_mbstring.dll --show-diff tests"
